// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://elnnpdepvvkuwnbsegrd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVsbm5wZGVwdnZrdXduYnNlZ3JkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM2MDI0NTcsImV4cCI6MjA0OTE3ODQ1N30.ckAoTH37l70TS2e5istPK4Tj6ZyeCogmq4qAH_SUBME";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);